---
name: Super-Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`.
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@v8.6.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_CHECKOV: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: true
          VALIDATE_JSCPD: true
          VALIDATE_YAML: true
          VALIDATE_YAML_PRETTIER: true
